### ISSUE TITLE
How Do I Customize Prompt with Additional Custom Prompts?

### ISSUE THREAD

**Issue by sheldonhull** [scrthq/PSProfile#1]
I have a folder of prompt ps1 files that allow for loading customized prompts, such as AWS Profile and Region name, posh-git status, and others. I'd like to see in the readme an example of how do I load these by customizing the prompt profile

**Comment by scrthq** [comment]
Hey @sheldonhull - I will likely roll this into the main module, but right now the Prompts functionality is in one of the included plugins. Here's how you currently add the plugin to your profile config:

```powershell
Import-Module PSProfile
$PSProfile.Plugins += @{
    Name = 'PSProfile.Prompt'
}
Save-PSProfile
$PSProfile.Load()
```

That should load the updated profile once you've saved it. This will be a bit more streamline in the near future (likely something like `Add-PSProfilePlugin -Name PSProfile.Prompt`)

Once you have it added, you should have some new functions available to enable prompt interaction:

`Save-Prompt`: This will do what you're looking to do and save your current prompt as a named prompt to call back later. For your use case, you'll want to...
1. Set your current prompt like you normally would
2. Run `Save-Prompt -Name $handyShortNameToRememberItBy` to save the current prompt in your PSProfile config.
3. Repeat for any additional prompts you have, giving each a unique name.

`Set-Prompt`: This is what you use to switch between prompts on your PSProfile config. If you only want to temporarily switch (i.e. not set the selected prompt as your default for persistence), include the `-Temporary` switch.

`Get-Prompt`: This will read back your current prompt's definition. Use the `-Raw` switch if you only want the prompt body, otherwise it will return a string containing the `function prompt { ... }` enclosure around it

`Edit-Prompt`: This will open your prompt for editing in Visual Studio Code using a temporary file. Once you make your edits, it will re-save your prompt on your PSProfile config and update it live so you can see your changes. VS Code is the only editor currently supported for this action.

**Comment by scrthq** [comment]
Update to this process using the latest version of the repo:

```powershell
Add-PSProfilePlugin -Name PSProfile.Prompt -Save
```

**Comment by sheldonhull** [comment]
Sweet. Gonna try this out for sure

**Comment by scrthq** [comment]
Updates on the released version, for reference:

`PSProfile.Prompt` has been rolled into the main code. All of the existing commands are still there, just as aliases instead pointing at the actual `*-PSProfile*` version:

`Edit-Prompt`
![image](https://user-images.githubusercontent.com/12724445/63310263-a2f4b900-c2bf-11e9-8339-fe7a22eefe16.png)

Also, if you want to try out my prompt, I include it with the default configuration (have a few people that have asked for it). You can check it out temporarily by running:

```powershell
Switch-Prompt SCRTHQ -Temporary
```

**Comment by sheldonhull** [comment]
Keeps getting better and better

**Comment by scrthq** [comment]
Hey @sheldonhull - going to close this out! Please let me know if you have any other questions regarding this 😄

**Comment by sheldonhull** [comment]
So I have a function that is a prompt for aws metadata. I want to leverage your prompt with all the existing functionality and add aws metadata, or lets say remove the `[#1]` session name you provided and instead plugin my prompt section. 

How do I build a prompt with "components" like you did? 
I'm struggling to find the configuration file that shows this so I can customize. 

Another good example. I use nameit to generate random names for sessions instead of numbered sessions. There's something great about `[Obtuse Penguin] [PS 5.1.1] [0:00:00.0910]` 😄 . Do you have a help doc I can refer to that shows how to construct the sections of a prompt so I can customize?

**Comment by sheldonhull** [comment]
@scrthq is it possible to use this approach like the `Add-PowerlinePrompt` or whatever does, where you can add several prompts together as "building blocks" like I mentioned? This would make it super easy to add to this or to an extensions repo a set of things like prebuilt aws prompt or other console features. 

Having to put it all in a single prompt block is pretty brittle for edits. Just wanted to follow-up and see if I'm missing something here or if it's an enhancement follow-up request
