### ISSUE TITLE
readme updates on credential storage

### ISSUE THREAD

**Issue by sheldonhull** [scrthq/PSProfile#13]
I really like what you mention in your readme on credentials storage, as I use bettercredentials. However, additional detail on how this works would be great. For instance, is this user specific using convertto-securestring? Can i include the credentials file in my work git repo as it's cached and encrypted to my key, or specific to machine etc? 

I'd love for a simpler way to use credentials in my scripts, but not clear exactly on this implementation.

**Comment by sheldonhull** [comment]
This is very helpful. 
So here's the gist of it for me. Based on this, what do you do to secure your "master" script that creates credentials for you instead it needs to be run on any machine?

Also, why do you find this better than storing in windows credential manager? I originally used a similar approach with exporting via clixml, but moved to BetterCredentials after that. I'd like to know what benefit you've gained so I can see it from another viewpoint. After answering totally feel free to close this. This is information gathering/learning for me at this point

**Comment by scrthq** [comment]
Hey @sheldonhull - If you are scripting the credential creation itself, then the Secrets concept within PSProfile probably isn't the ideal target since there isn't a guard around ExternalScripts invoked in the ScriptPaths currently. This may be worth expanding the Vault component to include a section for Secure Scripts, but they wouldn't be transferable due to being encrypted as SecureStrings via Data Protection API where the user/machine combo is the key to decrypt. I'm also imagining something like credential addition to the Secrets Vault being a one-and-done scenario, unless you're doing something like rotating credentials where the source is external (e.g. AWS Secrets Manager). Very open to ideas if there is value!

Regarding the Windows credential manager approach; if that works for you ala BetterCredentials or another management layer, then there is no reason to not continue doing what works for you! I personally had some issues with BetterCredentials causing other interactive scripts to fail that did require non-stored credentials since it clobbers `Get-Credential`, hence my decision to go this route personally. If you did want to include BetterCredentials, you can add the module to `$PSProfile.ModulesToInstall`, which will make sure that the module is installed on any machine you migrate/copy your PSProfile configuration over to =]

At the end of the day, it's YOUR PSProfile. Just because the options are there doesn't necessarily mean they have to be used if you have a more preferred way to do them! I definitely don't expect many people to use 100% of each concept.
