### ISSUE TITLE
Automatically update $PSProfile when secrets are added or removed

### ISSUE THREAD

**Issue by janegilring** [scrthq/PSProfile#29]
When adding a credential to the profile like this:
Add-PSProfileSecret -Save -Credential (Get-Credential -UserName domain\myuser)

Or this:
Add-PSProfileSecret -Save -Credential (Get-Credential -UserName me@somedomain.com)

Get-MyCreds is unable to find the secret:
Get-MyCreds -Item domain\myuser                                                                                                                                                             Get-MyCreds : Could not find secret item 'domain\myuser' in the PSProfileVault

**Update:** This was a mistake on my side, didn't realize I had to reload the profile for the newly added secret. And also that Get-PSProfileSecret is what I should have used. Hence, I'm updating the issue to suggest that the secrets should be automatically reloaded when adding or removing secrets :) Alternatively, write a warning stating that the newly added/removed credentials won`t be available until the PSProfile is reloaded.

**Comment by scrthq** [comment]
Hey @janegilring - Seeing if I can replicate, but they _should_ be saving by design; here's the high-level view of how the PSProfile configuration mgmt functions work:

1. `$PSProfile` object is updated with the appropriate change (e.g. add a Secret)
2. If `-Save` is included, write the current object back to the configuration file.

You current session should be accessing the `$PSProfile` object directly, so updating it in that first step should be covering that.

Seeing if I can replicate and figure it out as a bug! You're definitely describing the intended behavior =]

**Comment by janegilring** [comment]
Ah, I see. If -Save is omitted, the new secret is available immediately in the same session. However, then it won`t be stored in the configuration file and won't be available in any new sessions. Maybe it is a bug then, if -Save also should make it available immediately in the same session :)

**Comment by scrthq** [comment]
More that the session should be updated 100% of the time. When `-Save` is included, also save the current session configuration back to file

**Comment by scrthq** [comment]
Update rolled out in 0.6.0 - let me know if all is well!

**Comment by janegilring** [comment]
It works without issues now 👌

**Comment by scrthq** [comment]
Awesome!! Thank you for confirming!
